# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- fetch_github_code
- build
- analyze
- push
- test
fetch_github_code:
  stage: fetch_github_code
  image: alpine:latest
  before_script:
  - apk add --no-cache git
  script:
  - git clone https://github.com/vinay-14298/nodejs-app-project.git github_code
  - cd github_code
  - git checkout $GITHUB_BRANCH
  artifacts:
    paths:
    - github_code/
build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - cd github_code
  - ls -R
  - cd ecs-nodejs-mysql
  - docker build -t vinaybabuminnakanti2001/my_node_app:$CI_COMMIT_SHA .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker save vinaybabuminnakanti2001/my_node_app:$CI_COMMIT_SHA -o my_node_app.tar
  artifacts:
    paths:
    - github_code/ecs-nodejs-mysql/my_node_app.tar
  only:
  - main

sonarqube_analysis:
  stage: analyze
  image: maven:latest
  services:
    - docker:dind
  script:
    - cd github_code/ecs-nodejs-mysql/
    - docker run --rm -e SONAR_HOST_URL=$SONAR_HOST_URL -e SONAR_TOKEN=$SONAR_TOKEN -v $(pwd):/usr/src/app sonarsource/sonar-scanner-cli
  only:
    - main
push_to_dockerhub:
  stage: push
  image: docker:latest
  services:
  - docker:19.03.12-dind
  script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker load -i github_code/ecs-nodejs-mysql/my_node_app.tar
  - docker push vinaybabuminnakanti2001/my_node_app:$CI_COMMIT_SHA
  only:
  - main
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
